services:
  - type: web
    name: django-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: CELERY_BROKER_URL
        value: redis://red-cukvpr23esus73b1art0:6379/0

  - type: worker
    name: celery-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A core worker --loglevel=info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: CELERY_BROKER_URL
        value: redis://red-cukvpr23esus73b1art0:6379/0

  - type: worker
    name: celery-beat
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A core beat --loglevel=info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: CELERY_BROKER_URL
        value: redis://red-cukvpr23esus73b1art0:6379/0