# Generated by Django 5.1.5 on 2025-02-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investment_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-created_at']},
        ),
    ]
