# Generated by Django 5.1.5 on 2025-02-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_investment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
