# Generated by Django 5.1.5 on 2025-02-07 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('last_access', models.DateTimeField()),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('earned_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_withdrawal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_withdrawal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
    ]
