# Generated by Django 5.1.5 on 2025-02-11 23:12

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTC_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bitcoin Address')),
                ('ETH_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ethereum Address')),
                ('LTC_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Litecoin Address')),
                ('BCH_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bitcoin Cash Address')),
                ('XRP_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ripple Address')),
                ('ADA_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cardano Address')),
                ('DOT_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Polkadot Address')),
                ('SOL_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Solana Address')),
                ('DOGE_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dogecoin Address')),
                ('USDT_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tether Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Account',
                'verbose_name_plural': 'Payment Accounts',
            },
        ),
    ]
