# Generated by Django 5.1.5 on 2025-02-13 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPaymentAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTC_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bitcoin Address')),
                ('ETH_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ethereum Address')),
                ('LTC_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Litecoin Address')),
                ('BCH_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bitcoin Cash Address')),
                ('XRP_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ripple Address')),
                ('ADA_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cardano Address')),
                ('DOT_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Polkadot Address')),
                ('SOL_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Solana Address')),
                ('DOGE_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dogecoin Address')),
                ('USDT_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tether Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_payment_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Account',
                'verbose_name_plural': 'Payment Accounts',
            },
        ),
    ]
