# Generated by Django 5.1.5 on 2025-02-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_withdrawal_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='transactions.transaction'),
        ),
    ]
