# Generated by Django 5.1.5 on 2025-02-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_deposit_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_address_type',
            field=models.CharField(default='BTC', max_length=255),
            preserve_default=False,
        ),
    ]
