# Generated by Django 5.1.5 on 2025-02-08 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investment_is_active'),
        ('transactions', '0004_withdrawal_wallet_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='investments.investmentplan'),
        ),
    ]
