# Generated by Django 5.1.5 on 2025-02-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_deposit_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-created_at']},
        ),
    ]
